---
# tasks file for apache

    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    

    - name: Configure the haproxy cnf file with hosts
      template: src=000-default.conf.j2 dest=/etc/apache2/sites-enabled/000-default.conf
      notify: restart apache2
